dist: "bionic"  # https://docs.travis-ci.com/user/reference/overview/
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
env:  # https://www.djangoproject.com/download/
  - DJANGO=3.1.1 CRYPTOGRAPHY=3.1
  - DJANGO=3.1.1 CRYPTOGRAPHY=3.0
  - DJANGO=3.1.1 CRYPTOGRAPHY=2.9.2
  - DJANGO=3.1.1 CRYPTOGRAPHY=2.8
  - DJANGO=3.1.1 CRYPTOGRAPHY=2.7
  - DJANGO=3.0.10 CRYPTOGRAPHY=3.1
  - DJANGO=3.0.10 CRYPTOGRAPHY=3.0
  - DJANGO=3.0.10 CRYPTOGRAPHY=2.9.2
  - DJANGO=3.0.10 CRYPTOGRAPHY=2.8
  - DJANGO=3.0.10 CRYPTOGRAPHY=2.7
  - DJANGO=3.0.10 CRYPTOGRAPHY=3.1
  - DJANGO=2.2.16 CRYPTOGRAPHY=3.1
  - DJANGO=2.2.16 CRYPTOGRAPHY=2.9.2
  - DJANGO=2.2.16 CRYPTOGRAPHY=2.8
  - DJANGO=2.2.16 CRYPTOGRAPHY=2.7
install:
  # Build/test dependencies
 - pip install -U pip setuptools
 - pip install -r requirements/requirements-travis.txt
 - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
#before_script:
script:
  # download selenium driver
  - mkdir -p contrib/selenium 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar xf geckodriver-v0.26.0-linux64.tar.gz -C contrib/selenium

  - python dev.py code-quality
  - python dev.py coverage --format=text
  - echo -e "DEBUG = True\nSECRET_KEY = 'dummy'" > ca/ca/localsettings.py
  - python dev.py init-demo
  - python setup.py install
  - make -C docs html-check

matrix:
    exclude:
        # Django 3.0 doesn't support Python 3.5
        - env: DJANGO=3.1.1 CRYPTOGRAPHY=2.7
          python: "3.5"
        - env: DJANGO=3.1.1 CRYPTOGRAPHY=2.8
          python: "3.5"
        - env: DJANGO=3.1.1 CRYPTOGRAPHY=2.9.2
          python: "3.5"
        - env: DJANGO=3.1.1 CRYPTOGRAPHY=3.0
          python: "3.5"
        - env: DJANGO=3.1.1 CRYPTOGRAPHY=3.1
          python: "3.5"
        - env: DJANGO=3.0.10 CRYPTOGRAPHY=2.7
          python: "3.5"
        - env: DJANGO=3.0.10 CRYPTOGRAPHY=2.8
          python: "3.5"
        - env: DJANGO=3.0.10 CRYPTOGRAPHY=2.9.2
          python: "3.5"
        - env: DJANGO=3.0.10 CRYPTOGRAPHY=3.0
          python: "3.5"
        - env: DJANGO=3.0.10 CRYPTOGRAPHY=3.1
          python: "3.5"
