dist: "focal"  # https://docs.travis-ci.com/user/reference/overview/
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
    #- "nightly"
env:  # https://www.djangoproject.com/download/
  - DJANGO=3.1.4 CRYPTOGRAPHY=3.3.1
  - DJANGO=3.1.4 CRYPTOGRAPHY=3.2.1
  - DJANGO=3.1.4 CRYPTOGRAPHY=3.1
  - DJANGO=3.1.4 CRYPTOGRAPHY=3.0
  - DJANGO=2.2.17 CRYPTOGRAPHY=3.3.1
  - DJANGO=2.2.17 CRYPTOGRAPHY=3.2.1
  - DJANGO=2.2.17 CRYPTOGRAPHY=3.1
  - DJANGO=2.2.17 CRYPTOGRAPHY=3.0
install:
  # Build/test dependencies
  - pip install -U pip setuptools
  - pip install -r requirements/requirements-travis.txt
  - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
jobs:
  include:
    - stage: demo
      script: echo 1
    - script: echo 2
    - stage: test
    # download selenium driver
    - script: mkdir -p contrib/selenium 
    - script: wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
    - script: tar xf geckodriver-v0.26.0-linux64.tar.gz -C contrib/selenium

    - script: echo -e "DEBUG = True\nSECRET_KEY = 'dummy'" > ca/ca/localsettings.py
    - script: python dev.py code-quality
    - script: python dev.py coverage --format=text
    - script: python dev.py init-demo
    - script: python setup.py install
    - script: make -C docs html-check
