dist: "focal"  # https://docs.travis-ci.com/user/reference/overview/
language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
  #- "nightly"

# Enable pip cache: https://docs.travis-ci.com/user/caching/
cache: pip
env:  # https://www.djangoproject.com/download/
  global:
    - DJANGO_CA_SECRET_KEY=dummy
  jobs:
    - DJANGO=3.1.5 CRYPTOGRAPHY=3.3.1
    - DJANGO=3.1.5 CRYPTOGRAPHY=3.2.1
    - DJANGO=3.1.5 CRYPTOGRAPHY=3.1
    - DJANGO=3.1.5 CRYPTOGRAPHY=3.0
    - DJANGO=2.2.17 CRYPTOGRAPHY=3.3.1
    - DJANGO=2.2.17 CRYPTOGRAPHY=3.2.1
    - DJANGO=2.2.17 CRYPTOGRAPHY=3.1
    - DJANGO=2.2.17 CRYPTOGRAPHY=3.0
install:
  # Build/test dependencies
  - pip install -U pip setuptools wheel
  - pip install Django==$DJANGO cryptography==$CRYPTOGRAPHY
stages:
  - "Code Quality"
  - test
jobs:
  include:
    #- stage: test
    #  name: "Run test suite"
    - stage: "Code Quality"
      name: "Run isort and flake8"
      script:
        - pip install -r requirements/requirements-core.txt
        - pip install -r requirements/requirements-libs.txt
        - pip install -r requirements/requirements-lint.txt
        - ./dev.py code-quality
    - name: "Run pylint"
      script:
        # pylint requires libs to be installed for import tests
        - pip install -r requirements/requirements-core.txt
        - pip install -r requirements/requirements-libs.txt
        - pip install -r requirements/requirements-test.txt
        - pip install -r requirements/requirements-lint.txt
        - pylint --disable=fixme ca/django_ca/
    - name: "Generate documentation"
      script:
        # We need core/libs as conf.py has to call django.setup()
        - pip install -r requirements/requirements-core.txt
        - pip install -r requirements/requirements-libs.txt
        - pip install -r requirements/requirements-docs.txt
        - make -C docs html-check
    - name: "Initialize demo"
      script:
        # test libs are required for recreating fixtures
        - pip install -r requirements/requirements-core.txt termcolor
        - pip install -r requirements/requirements-libs.txt
        - pip install -r requirements/requirements-test.txt
        - python dev.py init-demo

script:
  - pip install -r requirements/requirements-core.txt
  - pip install -r requirements/requirements-libs.txt
  - pip install -r requirements/requirements-test.txt
  # download selenium driver
  - mkdir -p contrib/selenium
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
  - tar xf geckodriver-v0.26.0-linux64.tar.gz -C contrib/selenium
  - python dev.py coverage --format=text
  - python setup.py install
