commands:
    - command: docker-compose up -d
      clean:
          - docker-compose down -v
      display_output: |
          ...
          Creating {{ path.rstrip('/') | basename }}_backend_1  ... done
          Creating {{ path.rstrip('/') | basename }}_webserver_1 ... done
    - command: docker-compose ps
      waitfor:
          - command: sleep 5
      display_output: |
          Name                       Command               State         Ports
          -----------------------------------------------------------------------------------
          {{ path.rstrip('/') | basename }}_backend_1     ./celery.sh -l info              Up
          {{ path.rstrip('/') | basename }}_cache_1       docker-entrypoint.sh redis ...   Up
          {{ path.rstrip('/') | basename }}_db_1          docker-entrypoint.sh postgres    Up
          {{ path.rstrip('/') | basename }}_frontend_1    /bin/sh -c ./uwsgi.sh            Up
          {{ path.rstrip('/') | basename }}_webserver_1   /docker-entrypoint.sh /bin ...   Up    0.0.0.0:443->443/tcp,...
