name: Documentation
on:
  push:
  pull_request:
  pull_request_target:

jobs:

  run:
    runs-on: ubuntu-latest

    env:
      DJANGO_CA_SECRET_KEY: dummy

    steps:

      - name: Acquire sources
        uses: actions/checkout@v2.5.0

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.11
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements/requirements-docs.txt

      - name: doc8 style checks
        run: doc8 docs/source/

      - name: Generate documentation
        run: make -C docs html

      - name: Spelling
        run: make -C docs spelling
