name: type checking
on:
  push:
  pull_request:
  pull_request_target:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      DJANGO_CA_SECRET_KEY: dummy

    steps:

      - name: Acquire sources
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.11
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements/requirements-mypy.txt

      - name: run mypy
        run: mypy ca/django_ca/ docs/source/django_ca_sphinx/
