name: Tests
on:
  push:
  pull_request:
  pull_request_target:

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        django-version: [ "3.2.19", "4.1.9", "4.2.2" ]
        cryptography-version: [ "37.0.4", "39.0.2", "40.0.2", "41.0.1" ]

    env:
      DJANGO_CA_SECRET_KEY: dummy

    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, cryptography ${{ matrix.cryptography-version }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: os=${{ matrix.os }}-python=${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dependencies
        run: |
          echo "cryptography==${{ matrix.cryptography-version }}" > constraints.txt
          echo "django==${{ matrix.django-version }}" >> constraints.txt
          pip install -U pip setuptools wheel
          pip install -c constraints.txt -r requirements.txt -r requirements/requirements-test.txt -r requirements/requirements-docs.txt

      - name: Install program
        run: pip install -e .

      - name: Run tests
        run: |
          python dev.py init-demo
          python dev.py coverage --format=text
