name: Tests
on:
  push:
  pull_request:
  pull_request_target:

jobs:

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
        django-version: [ "3.2", "4.2" ]
        cryptography-version: [ "41" ]

    env:
      DJANGO_CA_SECRET_KEY: dummy

    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}, cryptography ${{ matrix.cryptography-version }}
    steps:

      - name: Acquire sources
        uses: actions/checkout@v3.1.0

      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Apply caching of dependencies
        uses: actions/cache@v3.0.11
        with:
          path: ~/.cache/pip
          key: os=${{ matrix.os }}-python=${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements-*.txt') }}

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -r requirements.txt -r requirements/requirements-test.txt -r requirements/requirements-docs.txt django~=${{ matrix.django-version }} cryptography~=${{ matrix.cryptography-version }}

      - name: Install program
        run: pip install -e .

      - name: Initialize demo
        run: python dev.py init-demo

      - name: Run tests
        run: pytest -v --cov-report term-missing --durations=20
